services:
  debezium.example:
    image: ${DOCKER_REGISTRY-}debeziumexample
    build:
      context: .
      dockerfile: Debezium.Example/Dockerfile
  console.consumer:
    image: ${DOCKER_REGISTRY-}consoleconsumer
    build:
      context: .
      dockerfile: Console.Consumer/Dockerfile

